### ISSUE TITLE
Exclude Library and Logs, .vs, and other files

### ISSUE THREAD

**Issue by tacman** [prof-smash/SettingsMenu-Complete#1]
This repo is unnecessarily large, in particular the /Library folder should be excluded, it will be rebuilt automatically when Unity opens the project.

Unfortunately, it's not as easy as deleting the directory and adding Library to .gitignore, since the repo will still contain the older versions, since mine is the only fork it's probably easiest to delete this repo entirely and re-create it with the minimum amount of files (Assets, Packages, ProjectSettings).

Also, please add a README with a link back to your excellent article!

**Comment by prof-smash** [comment]
Hey!

Apologies for the late response. Somehow, I did not know this about Unity. Thanks for sharing!

I'll be addressing this in the coming days, just have to set aside some time to do it. Mainly letting you know that I have seen your comment and, as you suggested, the repo will likely be recreated with this one being deleted. Both this and the codeless version should see this change. I'll also be remembering this with any future repos. Thanks!

**Comment by tacman** [comment]
Sure.  This is the .gitignore I use

```
# This .gitignore file should be placed at the root of your Unity project directory
#
# Get latest from https://github.com/github/gitignore/blob/master/Unity.gitignore
#
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Mm]emoryCaptures/

# Asset meta data should only be ignored when the corresponding asset is also ignored


# Uncomment this line if you wish to ignore the asset store tools plugin
# /[Aa]ssets/AssetStoreTools*

# Autogenerated Jetbrains Rider plugin
[Aa]ssets/Plugins/Editor/JetBrains*

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.unitypackage

# Crashlytics generated file
crashlytics-build.properties


/vendor/
```
